fix: Change error on missing Java dependency to warning

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,4 +1,3 @@
-#!/usr/bin/env bash
 
 installer() {
   local install_type=$1
@@ -9,10 +8,8 @@ installer() {
   tmp_download_dir=$(mktemp -d -t jib_XXXXXXX)
 
   if ! which java >/dev/null; then
-    echo "You need a Java Runtime already installed on your computer."
-    echo "Follow the instructions for your platform or download it"
-    echo "from http://java.com/en/download"
-    exit 1
+    echo "WARNING: Java Runtime not found on your system." >&2
+    echo "Jib requires Java to run. Java can be installed with Mise" >&2
   fi
 
   if [ "version" != "${install_type}" ]; then
